# Generated by Django 4.1.6 on 2023-02-08 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_header",
                    models.CharField(max_length=100, verbose_name="название поста"),
                ),
                ("post_text", models.TextField(verbose_name="текст поста")),
                (
                    "post_view",
                    models.IntegerField(verbose_name="количество просмотров"),
                ),
                (
                    "post_create_date",
                    models.DateTimeField(verbose_name="дата создания поста"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment_text",
                    models.CharField(max_length=300, verbose_name="текст коммента"),
                ),
                (
                    "comment_create_date",
                    models.DateTimeField(verbose_name="дата создания коммента"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="posts.post"
                    ),
                ),
            ],
        ),
    ]
